# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = false
favicon = "/favicon.png"

[footer]
since = 2025
customText = "Ink and Think! <br> We don’t use cookies. We do use <a href='https://www.goatcounter.com/' target='_blank'>GoatCounter</a>, a privacy-friendly open-source analytics tool, to understand which posts are getting attention. If you’re using an ad blocker, please consider disabling it for this site—otherwise the counter might not register your visit."

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = ""
subtitle = "Ink and Think!"

[sidebar.avatar]
enabled = true
local = true
src = "img/logo.png"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "dmkoder/blogic-comments"
repoID = "R_kgDOQLwBtQ"
category = "General"
categoryID = "DIC_kwDOQLwBtc4CxO_1"
mapping = "pathname"
lightTheme = "noborder_light"
darkTheme = "noborder_gray"
reactionsEnabled = 1
emitMetadata = 0
